stages:
  - build

rust-latest:
  stage: build
  image: docker.artifactory.ea.com/rust:latest
  script:
    - rustc --version --verbose && cargo --version --verbose  # Print version info for debugging
    - apt-get update -yqq
    - apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev mingw-w64
    - RUSTFLAGS='-C target-feature=+crt-static'
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --release --target x86_64-pc-windows-gnu --verbose
    - pwd
    - ls target/x86_64-pc-windows-gnu/release
    - mkdir artifacts
    - cp target/x86_64-pc-windows-gnu/release/log-viewer-rs.exe artifacts
  artifacts:
    paths:
    - artifacts